// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jsonc

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc(in *jlexer.Lexer, out *message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "operation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Operation = string(in.String())
			}
		case "transfers":
			if in.IsNull() {
				in.Skip()
				out.Transfers = nil
			} else {
				in.Delim('[')
				if out.Transfers == nil {
					if !in.IsDelim(']') {
						out.Transfers = make([]jsonTransfer, 0, 0)
					} else {
						out.Transfers = []jsonTransfer{}
					}
				} else {
					out.Transfers = (out.Transfers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 jsonTransfer
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Transfers = append(out.Transfers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "accounts":
			if in.IsNull() {
				in.Skip()
				out.Accounts = nil
			} else {
				in.Delim('[')
				if out.Accounts == nil {
					if !in.IsDelim(']') {
						out.Accounts = make([]jsonAccount, 0, 0)
					} else {
						out.Accounts = []jsonAccount{}
					}
				} else {
					out.Accounts = (out.Accounts)[:0]
				}
				for !in.IsDelim(']') {
					var v2 jsonAccount
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.Accounts = append(out.Accounts, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc(out *jwriter.Writer, in message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation\":"
		out.RawString(prefix[1:])
		out.String(string(in.Operation))
	}
	{
		const prefix string = ",\"transfers\":"
		out.RawString(prefix)
		if in.Transfers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Transfers {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"accounts\":"
		out.RawString(prefix)
		if in.Accounts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Accounts {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc(l, v)
}
func easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc1(in *jlexer.Lexer, out *jsonTransfer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "debit_account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DebitAccountID = string(in.String())
			}
		case "credit_account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditAccountID = string(in.String())
			}
		case "pending_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PendingID = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "ledger":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ledger = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "flags":
			if in.IsNull() {
				in.Skip()
				out.Flags = nil
			} else {
				in.Delim('[')
				if out.Flags == nil {
					if !in.IsDelim(']') {
						out.Flags = make([]string, 0, 4)
					} else {
						out.Flags = []string{}
					}
				} else {
					out.Flags = (out.Flags)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.Flags = append(out.Flags, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "user_data_128":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData128 = string(in.String())
			}
		case "user_data_64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData64 = uint64(in.Uint64())
			}
		case "user_data_32":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData32 = uint32(in.Uint32())
			}
		case "timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeout = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc1(out *jwriter.Writer, in jsonTransfer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"debit_account_id\":"
		out.RawString(prefix)
		out.String(string(in.DebitAccountID))
	}
	{
		const prefix string = ",\"credit_account_id\":"
		out.RawString(prefix)
		out.String(string(in.CreditAccountID))
	}
	{
		const prefix string = ",\"pending_id\":"
		out.RawString(prefix)
		out.String(string(in.PendingID))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"ledger\":"
		out.RawString(prefix)
		out.String(string(in.Ledger))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		if in.Flags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Flags {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"user_data_128\":"
		out.RawString(prefix)
		out.String(string(in.UserData128))
	}
	{
		const prefix string = ",\"user_data_64\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserData64))
	}
	{
		const prefix string = ",\"user_data_32\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UserData32))
	}
	{
		const prefix string = ",\"timeout\":"
		out.RawString(prefix)
		out.String(string(in.Timeout))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonTransfer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonTransfer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonTransfer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonTransfer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc1(l, v)
}
func easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc2(in *jlexer.Lexer, out *jsonAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "ledger":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ledger = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "flags":
			if in.IsNull() {
				in.Skip()
				out.Flags = nil
			} else {
				in.Delim('[')
				if out.Flags == nil {
					if !in.IsDelim(']') {
						out.Flags = make([]string, 0, 4)
					} else {
						out.Flags = []string{}
					}
				} else {
					out.Flags = (out.Flags)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					out.Flags = append(out.Flags, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "user_data_128":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData128 = string(in.String())
			}
		case "user_data_64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData64 = uint64(in.Uint64())
			}
		case "user_data_32":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData32 = uint32(in.Uint32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc2(out *jwriter.Writer, in jsonAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"ledger\":"
		out.RawString(prefix)
		out.String(string(in.Ledger))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		if in.Flags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Flags {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"user_data_128\":"
		out.RawString(prefix)
		out.String(string(in.UserData128))
	}
	{
		const prefix string = ",\"user_data_64\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserData64))
	}
	{
		const prefix string = ",\"user_data_32\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UserData32))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22dba252EncodeGithubComMi7teRKafkaTbInternalCodecJsonc2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22dba252DecodeGithubComMi7teRKafkaTbInternalCodecJsonc2(l, v)
}
