// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package emit

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit(in *jlexer.Lexer, out *Source) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "topic":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Topic = string(in.String())
			}
		case "partition":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Partition = int32(in.Int32())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit(out *jwriter.Writer, in Source) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"topic\":"
		out.RawString(prefix[1:])
		out.String(string(in.Topic))
	}
	{
		const prefix string = ",\"partition\":"
		out.RawString(prefix)
		out.Int32(int32(in.Partition))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Source) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Source) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Source) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Source) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit(l, v)
}
func easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit1(in *jlexer.Lexer, out *ResultsMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Source).UnmarshalEasyJSON(in)
			}
		case "results":
			if in.IsNull() {
				in.Skip()
				out.Results = nil
			} else {
				in.Delim('[')
				if out.Results == nil {
					if !in.IsDelim(']') {
						out.Results = make([]ResultEntry, 0, 1)
					} else {
						out.Results = []ResultEntry{}
					}
				} else {
					out.Results = (out.Results)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ResultEntry
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Results = append(out.Results, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "emitted_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EmitTS = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit1(out *jwriter.Writer, in ResultsMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix[1:])
		(in.Source).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"results\":"
		out.RawString(prefix)
		if in.Results == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Results {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"emitted_at\":"
		out.RawString(prefix)
		out.String(string(in.EmitTS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResultsMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultsMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResultsMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultsMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit1(l, v)
}
func easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit2(in *jlexer.Lexer, out *ResultEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = int(in.Int())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit2(out *jwriter.Writer, in ResultEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Error != "" {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResultEntry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultEntry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa936608EncodeGithubComMi7teRKafkaTbInternalEmit2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResultEntry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultEntry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa936608DecodeGithubComMi7teRKafkaTbInternalEmit2(l, v)
}
