// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cdc

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc(in *jlexer.Lexer, out *Transfer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "pending_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PendingID = string(in.String())
			}
		case "user_data_128":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData128 = string(in.String())
			}
		case "user_data_64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData64 = uint64(in.Uint64())
			}
		case "user_data_32":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData32 = uint32(in.Uint32())
			}
		case "timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeout = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "flags":
			if in.IsNull() {
				in.Skip()
				out.Flags = nil
			} else {
				in.Delim('[')
				if out.Flags == nil {
					if !in.IsDelim(']') {
						out.Flags = make([]string, 0, 4)
					} else {
						out.Flags = []string{}
					}
				} else {
					out.Flags = (out.Flags)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Flags = append(out.Flags, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc(out *jwriter.Writer, in Transfer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	if in.PendingID != "" {
		const prefix string = ",\"pending_id\":"
		out.RawString(prefix)
		out.String(string(in.PendingID))
	}
	if in.UserData128 != "" {
		const prefix string = ",\"user_data_128\":"
		out.RawString(prefix)
		out.String(string(in.UserData128))
	}
	if in.UserData64 != 0 {
		const prefix string = ",\"user_data_64\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserData64))
	}
	if in.UserData32 != 0 {
		const prefix string = ",\"user_data_32\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UserData32))
	}
	if in.Timeout != "" {
		const prefix string = ",\"timeout\":"
		out.RawString(prefix)
		out.String(string(in.Timeout))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		if in.Flags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Flags {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transfer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transfer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transfer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transfer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc(l, v)
}
func easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc1(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = string(in.String())
			}
		case "checkpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Checkpoint = string(in.String())
			}
		case "ledger":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ledger = string(in.String())
			}
		case "transfer":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Transfer).UnmarshalEasyJSON(in)
			}
		case "debit_account":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DebitAccount).UnmarshalEasyJSON(in)
			}
		case "credit_account":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.CreditAccount).UnmarshalEasyJSON(in)
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc1(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	{
		const prefix string = ",\"checkpoint\":"
		out.RawString(prefix)
		out.String(string(in.Checkpoint))
	}
	{
		const prefix string = ",\"ledger\":"
		out.RawString(prefix)
		out.String(string(in.Ledger))
	}
	{
		const prefix string = ",\"transfer\":"
		out.RawString(prefix)
		(in.Transfer).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"debit_account\":"
		out.RawString(prefix)
		(in.DebitAccount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"credit_account\":"
		out.RawString(prefix)
		(in.CreditAccount).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc1(l, v)
}
func easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc2(in *jlexer.Lexer, out *Account) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "debits_pending":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DebitsPending = string(in.String())
			}
		case "debits_posted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DebitsPosted = string(in.String())
			}
		case "credits_pending":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditsPending = string(in.String())
			}
		case "credits_posted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditsPosted = string(in.String())
			}
		case "user_data_128":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData128 = string(in.String())
			}
		case "user_data_64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData64 = uint64(in.Uint64())
			}
		case "user_data_32":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserData32 = uint32(in.Uint32())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "flags":
			if in.IsNull() {
				in.Skip()
				out.Flags = nil
			} else {
				in.Delim('[')
				if out.Flags == nil {
					if !in.IsDelim(']') {
						out.Flags = make([]string, 0, 4)
					} else {
						out.Flags = []string{}
					}
				} else {
					out.Flags = (out.Flags)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.Flags = append(out.Flags, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc2(out *jwriter.Writer, in Account) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"debits_pending\":"
		out.RawString(prefix)
		out.String(string(in.DebitsPending))
	}
	{
		const prefix string = ",\"debits_posted\":"
		out.RawString(prefix)
		out.String(string(in.DebitsPosted))
	}
	{
		const prefix string = ",\"credits_pending\":"
		out.RawString(prefix)
		out.String(string(in.CreditsPending))
	}
	{
		const prefix string = ",\"credits_posted\":"
		out.RawString(prefix)
		out.String(string(in.CreditsPosted))
	}
	if in.UserData128 != "" {
		const prefix string = ",\"user_data_128\":"
		out.RawString(prefix)
		out.String(string(in.UserData128))
	}
	if in.UserData64 != 0 {
		const prefix string = ",\"user_data_64\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserData64))
	}
	if in.UserData32 != 0 {
		const prefix string = ",\"user_data_32\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.UserData32))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		if in.Flags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Flags {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Account) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Account) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComMi7teRKafkaTbInternalCdc2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Account) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Account) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComMi7teRKafkaTbInternalCdc2(l, v)
}
